### ISSUE TITLE
Reconciliate the differences between server and client

### ISSUE THREAD

**Issue by kxplxn** [kxplxn/goteam#121]
While re-writing the backend in Go, I've made a few changes to app design:

1. team table is removed, users can instead be assigned directly to each board
2. invites are removed, users can instead be assigned via their username by board admin
3. task assignment is removed

However, in terms of effort to reward, it makes more sense to revert these changes than to refactor the client to comply with them. Refactoring the backend will:
1. take less time
2. offer more functionality

### Tasks
- [x] create table team with invite code and admin columns
- [x] add assignee column to task
- [x] register
  - [x] check whether invite-code query parameter exists
    - [x] if it does not, create a new team for the user with a new board and tutorial tasks  
    - [x] if it does, validate and add user to that team
- [x] check whether the user is team admin
    - [x] DELETE board
    - [x] PATCH board
    - [x] POST board
    - [x] PATCH column
    - [x] POST task
    - [x] PATCH task
    - [x] DELETE task
    - [x] PATCH subtask 
 - [x] remove table user_board
 - [x] remove package dbaccess/userboard
 - [x] remove dbaccess/RelSelector
 - [x] GET board
   - [x] return entire client state
   - [x] if ID is empty, set the activeBoard to the first board for the user's team
   - [x] If no board exists for the user's team, create one ???
     - Find out how this was handled in the Django version of the app
 - [x] refactor
     - [x] move user retrieve/isadmin checks before other db operations
